#
# kano-mount-trigger Makefile
#
# Copyright (C) 2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# Copyright (C) 2016 Alfabook srl
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
# rebadged with microninja
#
# A short program which triggers an action when sent a signal

all: microninja-mount-trigger

microninja-mount-trigger: microninja-mount-trigger.c
	gcc microninja-mount-trigger.c -o microninja-mount-trigger

